'''
Load an old simulation to test regression.

Saved file originally generated by checking out Covasim v1.7.0 (with this file
not checked in) and running:

    import test_regression as tr
    tr.make_sim(do_save=True)
'''

import sciris as sc
import covasim as cv
import pytest

pop_size = 500
filename = 'example_regression.sim'
version = '1.7.0'


def make_sim(do_save=False, **kwargs):

    # Shared settings
    pars = dict(pop_size=pop_size, verbose=0)
    pars.update(kwargs)

    # Versioning was introduced in 2.0
    if cv.check_version('2.0.0', verbose=False) >= 0:
        pars.update({'version':version})

    sim = cv.Sim(**pars)
    sim.run()

    if do_save:
        print(sim.summary)
        sim.save(filename)

    return sim


@pytest.mark.skip(reason='Retired in v4.0: the v1.7.0 example_regression.sim pickle predates the '
                         'Starsim object model and cannot be unpickled. The v4 regression guard is '
                         'the multi-seed parity gate (tests/migrate3to4/) + test_baselines.py.')
def test_regression():
    sc.heading('Testing regression...')

    sim1 = cv.load(filename)
    sim2 = make_sim()

    # Check that they match, skipping r_eff which changed
    cv.diff_sims(sim1, sim2, skip_key_diffs=True, skip='r_eff', die=True)

    # Confirm that non-matching sims don't match
    sim3 = make_sim(beta=0.02123)
    with pytest.raises(ValueError):
        cv.diff_sims(sim1, sim3, skip_key_diffs=True, die=True)

    return sim1, sim2


#%% Run as a script
if __name__ == '__main__':

    # Start timing and optionally enable interactive plotting
    T = sc.tic()

    sim1, sim2 = test_regression()

    sc.toc(T)
    print('Done.')
